import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// --- START: Custom esbuild plugin for 'process/' import ---
const fixProcessImportPlugin = {
  name: 'fix-process-import', // A unique name for your plugin
  setup(build) {
    // This hook runs when esbuild tries to resolve a module path.
    // The filter /^process\/?$/ matches 'process' or 'process/'
    build.onResolve({ filter: /^(process|string_decoder)\/?$/ }, args => {
      // Check if it's an actual require or import statement
      if (args.kind === 'require-call' || args.kind === 'import-statement') {
        // If it is, tell esbuild to resolve it to the Node.js built-in 'process'
        // and mark it as external (meaning, don't bundle it, assume it's available globally)
        return { path: 'process', external: true };
      }
      return null; // Let other resolvers handle it if it doesn't match our criteria
    });
  },
};
// --- START: Custom esbuild plugin for clean browser polyfills (removing IE/DOM script injection) ---
const cleanPolyfillsPlugin = {
  name: 'clean-polyfills',
  setup(build) {
    // Intercept 'immediate' and 'setimmediate' imports/requires from jszip/lie
    build.onResolve({ filter: /^(immediate|setimmediate)$/ }, args => {
      return { path: args.path, namespace: 'clean-polyfills' };
    });
    // Provide clean, modern shims without any script tags or eval/Function
    build.onLoad({ filter: /.*/, namespace: 'clean-polyfills' }, args => {
      if (args.path === 'immediate') {
        return {
          contents: `module.exports = function immediate(task) {
  if (typeof setImmediate === 'function') {
    setImmediate(task);
  } else {
    setTimeout(task, 0);
  }
};`,
          loader: 'js'
        };
      }
      if (args.path === 'setimmediate') {
        return {
          contents: `if (typeof global !== 'undefined' && typeof global.setImmediate === 'undefined') {
  global.setImmediate = function(fn, ...args) { return setTimeout(fn, 0, ...args); };
  global.clearImmediate = function(id) { clearTimeout(id); };
}
if (typeof window !== 'undefined' && typeof window.setImmediate === 'undefined') {
  window.setImmediate = function(fn, ...args) { return setTimeout(fn, 0, ...args); };
  window.clearImmediate = function(id) { clearTimeout(id); };
}
module.exports = {
  setImmediate: typeof setImmediate !== 'undefined' ? setImmediate : setTimeout,
  clearImmediate: typeof clearImmediate !== 'undefined' ? clearImmediate : clearTimeout
};`,
          loader: 'js'
        };
      }
    });
  }
};
// --- END: Custom esbuild plugin ---

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		'process',
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	platform: "node",
	plugins: [fixProcessImportPlugin, cleanPolyfillsPlugin]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}